package com.anyuaning.osp.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.anyuaning.osp.model.sport.Timing;

import com.anyuaning.osp.dao.sport.TimingDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig timingDaoConfig;

    private final TimingDao timingDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        timingDaoConfig = daoConfigMap.get(TimingDao.class).clone();
        timingDaoConfig.initIdentityScope(type);

        timingDao = new TimingDao(timingDaoConfig, this);

        registerDao(Timing.class, timingDao);
    }
    
    public void clear() {
        timingDaoConfig.getIdentityScope().clear();
    }

    public TimingDao getTimingDao() {
        return timingDao;
    }

}
