package com.anyuaning.osp.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.anyuaning.osp.model.sport.Timing;
import com.anyuaning.osp.model.sport.Jogging;

import com.anyuaning.osp.dao.sport.TimingDao;
import com.anyuaning.osp.dao.sport.JoggingDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig timingDaoConfig;
    private final DaoConfig joggingDaoConfig;

    private final TimingDao timingDao;
    private final JoggingDao joggingDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        timingDaoConfig = daoConfigMap.get(TimingDao.class).clone();
        timingDaoConfig.initIdentityScope(type);

        joggingDaoConfig = daoConfigMap.get(JoggingDao.class).clone();
        joggingDaoConfig.initIdentityScope(type);

        timingDao = new TimingDao(timingDaoConfig, this);
        joggingDao = new JoggingDao(joggingDaoConfig, this);

        registerDao(Timing.class, timingDao);
        registerDao(Jogging.class, joggingDao);
    }
    
    public void clear() {
        timingDaoConfig.getIdentityScope().clear();
        joggingDaoConfig.getIdentityScope().clear();
    }

    public TimingDao getTimingDao() {
        return timingDao;
    }

    public JoggingDao getJoggingDao() {
        return joggingDao;
    }

}
