package com.anyuaning.osp.model.sport;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TIMING.
 */
public class Timing {

    private Long id;
    private java.util.Date startTime;
    private java.util.Date endTime;
    private String startFormatterTime;
    private String endFormatterTime;
    private Long length;

    public Timing() {
    }

    public Timing(Long id) {
        this.id = id;
    }

    public Timing(Long id, java.util.Date startTime, java.util.Date endTime, String startFormatterTime, String endFormatterTime, Long length) {
        this.id = id;
        this.startTime = startTime;
        this.endTime = endTime;
        this.startFormatterTime = startFormatterTime;
        this.endFormatterTime = endFormatterTime;
        this.length = length;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getStartTime() {
        return startTime;
    }

    public void setStartTime(java.util.Date startTime) {
        this.startTime = startTime;
    }

    public java.util.Date getEndTime() {
        return endTime;
    }

    public void setEndTime(java.util.Date endTime) {
        this.endTime = endTime;
    }

    public String getStartFormatterTime() {
        return startFormatterTime;
    }

    public void setStartFormatterTime(String startFormatterTime) {
        this.startFormatterTime = startFormatterTime;
    }

    public String getEndFormatterTime() {
        return endFormatterTime;
    }

    public void setEndFormatterTime(String endFormatterTime) {
        this.endFormatterTime = endFormatterTime;
    }

    public Long getLength() {
        return length;
    }

    public void setLength(Long length) {
        this.length = length;
    }

}
